name: model-test-and-deploy
on:
  workflow_call:
    inputs:
      model_files:
        required: true
        type: string
      model_prefix:
        required: true
        type: string
      event_name:
        required: false
        type: string
    secrets:
      docker_repo:
        required: true
      docker_svc:
        required: true
      repo_user:
        required: true
      repo_pw:
        required: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Validate MDF
        env:
          FILES: ${{ inputs.model_files }}
        run: |
          echo $PWD
          pip install bento-mdf/drivers/python
          pushd model-desc
          test-mdf.py --log-file validate.log $FILES
          # git config user.name github-actions
          # git add validate.log
          # git commit -m "record validation log"
          # git push
        shell: bash
  build:
    runs-on: ubuntu-latest
    needs: validate
    if: ${{ inputs.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Build model artifacts
        env:
          REPO: ${{ secrets.docker_repo }}
          RSVC: ${{ secrets.docker_svc }}
          USER: ${{ secrets.repo_user }}
          PW: ${{ secrets.repo_pw }}
          MODEL: ${{ inputs.model_prefix }}
          FILES: ${{ inputs.model_files }}
        run: |
          pushd model-desc
          cp -aR ../bento-mdf/drivers/Perl/make-model/lib lib
          cp -aR ../bento-mdf/drivers/Perl/make-model/bin bin
          # run model-tool with pre-built perl - fast
          docker login -u $USER -p $PW $RSVC
          docker run -v "$PWD":/home/user -w /home/user $RSVC/$REPO/model-tool-perl:latest -Ilib bin/model-tool -g update-model.svg -T update-model.txt $FILES
          echo repo $(git remote get-url origin) > update-info.txt
          # second to last commit is ours, last commit is travis'
          echo commit $(git log -2 --pretty=format:"%h" | tail -1) >> update-info.txt
          cat update-info.txt
          cat update-info.txt update-model.txt > x.txt
          cp -f x.txt update-model.txt
          cp $FILES ../docs/model-desc
          cp update-model.txt ../docs/model-desc/${MODEL}.txt
          sed -e '1,6d' update-model.svg > ../docs/model-desc/${MODEL}.svg
          rm -f update-model.svg update-info.txt x.txt update-model.txt
          pushd ../docs
          cat ./README.md.content > ./README.md
          echo "<div id='graph' style='display:off;'>" >> ./README.md
          cat ./model-desc/${MODEL}.svg >> ./README.md
          echo "</div>" >> ./README.md
          popd
      - name: Commit artifacts to docs
        run: |
          git config user.name github-actions
          git add docs
          git commit -m "deploy artifacts to github page"
          git push
        shell: bash
